print("Welcome to 4k club from Machakos school")
print("Fill in your details here")
name=input("Enter your name:")
classroom=input("Enter your class:")
Reasonfortryingtojoin=input("Please right why you want to join our club:")
Reasonforlettingyouintoourclub=input("Please let us know why we should let you into our club:")
print(name)
print(classroom)
print(Reasonfortryingtojoin)
print(Reasonforlettingyouintoourclub)

print("NOW OFFICIALLY PART OF 4K CLUB")
